// +build !ignore_autogenerated

/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package annotations

import (
	v1 "k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Aliases != nil {
		in, out := &in.Aliases, &out.Aliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.BasicDigestAuth = in.BasicDigestAuth
	out.Canary = in.Canary
	out.CertificateAuth = in.CertificateAuth
	out.Connection = in.Connection
	out.CorsConfig = in.CorsConfig
	if in.CustomHTTPErrors != nil {
		in, out := &in.CustomHTTPErrors, &out.CustomHTTPErrors
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.DefaultBackend != nil {
		in, out := &in.DefaultBackend, &out.DefaultBackend
		*out = new(v1.Service)
		(*in).DeepCopyInto(*out)
	}
	in.FastCGI.DeepCopyInto(&out.FastCGI)
	if in.Denied != nil {
		in, out := &in.Denied, &out.Denied
		*out = new(string)
		**out = **in
	}
	in.ExternalAuth.DeepCopyInto(&out.ExternalAuth)
	out.Opentracing = in.Opentracing
	out.Proxy = in.Proxy
	out.ProxySSL = in.ProxySSL
	in.RateLimit.DeepCopyInto(&out.RateLimit)
	out.Redirect = in.Redirect
	out.Rewrite = in.Rewrite
	out.SecureUpstream = in.SecureUpstream
	out.SessionAffinity = in.SessionAffinity
	out.UpstreamHashBy = in.UpstreamHashBy
	in.Whitelist.DeepCopyInto(&out.Whitelist)
	out.SSLCipher = in.SSLCipher
	out.Logs = in.Logs
	out.InfluxDB = in.InfluxDB
	out.ModSecurity = in.ModSecurity
	out.Mirror = in.Mirror
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}
